### PR TITLE
Fixed Likes and Comment Visibility & Refactored code and styles

### LINKED ISSUE #206: Comments not visible in the comment list.
**Describe the bug**
After adding a comment, it is not visible in the comment list.

**To Reproduce**
1. Navigate to the podcast then episode where comments can be added.
2. Click on comment icon to open up the comments modal.
3. Input a text and submit the comment
4. Check the comment list to confirm whether the submitted comment is visible.

### PR DESCRIPTION
**Pull request by Radwanbaba13**
This merge request has made several changes and fixes to the Comment and Like componenets:

- The episode/comment likes not shows if the user has liked it before, thanks to the new isLiked endpoint.
- The the comment modal rerenders everytime a comment or reply is added, fixing the visibility bug we had.
- Added validation for reply and comments (Replies were able to be posted even if they were empty).
- Restyled the comment component to be more user friendly by relocating the text/icons and widening the modal to fit more content. 
- Refactored code to be more comprehensible and clean, by adding comments and deleting unnecessary functions and variables.

Closes #206

### CODE REVIEW

File: frontend/components/social/likeComponent.tsx [hunk 1]
```diff
@@ -1,16 +1,27 @@
...
-  const [likes, setLikes] = useState(initialLikes); // State to track the number of likes
-  const [isLiked, setIsLiked] = useState(initialIsLiked); // State to track whether the episode or comment is liked
+const LikeComponent = ({ episodeOrCommentId, initialLikes }) => {
+  // Component Values
+  const [likes, setLikes] = useState(initialLikes);
+
+  const [isLiked, setIsLiked] = useState(false);
+
+  useEffect(() => {
+    const fetchData = async () => {
```
Comment (mathieutrudeau) [inline frontend/components/social/likeComponent.tsx:14]: Did not know you could define async methods within useEffect(). Thats neat!

**Review by mathieutrudeau — APPROVED** [review]
Good work.

**Review by Ahed752 — APPROVED** [review]
Great work on enhancing the Like and Comment components! The isLiked integration and visibility fixes greatly improve user experience.
