### PR TITLE
Fixed bug where prodcast metric was always returning 0. Added more metrics

### LINKED ISSUE #331: Podcast metrics endpoint does not return updated values
**Describe the bug**
The metrics endpoint returns not up-to-date updated information of the podcast.

**To Reproduce**
1. Create a new Podcast and episode
2. Like and comment on the episode
3. Go to CreatorHub
4. See that it is still 0 likes and 0 comments in the metrics section

**Screenshots**
image
image
image

### PR DESCRIPTION
**Pull request by shadijiha**
Fixed bug where the Podcast Episodes, Likes and Comments collections where always empty before no `Include` and `ThenInclude` were used

Also added Age histogram and Gender metrics

Closes #331 
Updates #23

### CODE REVIEW

File: Backend/Backend/Services/Interfaces/IPodcastService.cs [hunk 1]
```diff
@@ -32,6 +32,6 @@ public interface IPodcastService
     public Task<bool> EditEpisodeTranscriptLinesAsync(User user,Guid episodeId, TranscriptLineResponse[] lines);
     public Task<ListenPositionResponse> GetWatchHistory(User user, Guid episodeId);
     public Task<AdjecentEpisodeResponse> GetAdjecentEpisodeAsync(Guid episodeId);
-    public Task<object?> GetMetrics(User user, Guid podcastId);
+    public Task<object?> GetMetrics(User user, Guid podcastId, string domainUrl);
```
Comment (mathieutrudeau) [inline Backend/Backend/Services/Interfaces/IPodcastService.cs:35]: Creating a custom Response definition might be better than having type object?. It would definitely make the code more robust.

**Review by mathieutrudeau — APPROVED** [review]

File: Backend/Backend/Services/Interfaces/IPodcastService.cs (hunk 1 above)
Comment (shadijiha) [reply Backend/Backend/Services/Interfaces/IPodcastService.cs]: Done!

**Review by BigSaladMan — APPROVED** [review]
LGTM

**Comment by soni2261** [comment]
please fix those errors 
image
